[project]
name = "flowise-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bert-score>=0.3.13",
    "fastapi>=0.136.3",
    "fastembed>=0.8.0",
    "langchain-core>=1.4.7",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.3.2",
    "langchain-qdrant>=1.1.0",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.5",
    "litellm[proxy]>=1.88.1",
    "nltk>=3.9.4",
    "openai>=2.41.1",
    "pydantic-settings>=2.14.1",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.18.0",
    "rouge-score>=0.1.2",
    "sentence-transformers>=5.6.0",
    "sentencepiece>=0.2.1",
    "uvicorn>=0.49.0",
]
